####
# Only this file is to be changed when running the pipeline (and the Snakefile rule all)
####


# sequencing type: either DNA (DNA = true) or RNA (DNA = false)
DNA_seq: True

# path/to/refgenome.fa
ref: "resources/reference/hg38.fa"
ref_index: "resources/reference/hg38.fa.fai"

#TESTING PURPOSES:
ref_fil: "results/filter_ref/hg38_filtered.fa"

# set either data_dir or samples, the other one should be false
# directory where the data is (or the symlink to the data)
data_dir: "resources/data"
# path to sample sheet as tsv provided by user which looks like sample|fq1|fq2
samples: False

# for trimming, path/to/adaptersequence.fa
adapter: "resources/adapter/panel-adapter.fa"

# path/to/paneldesign.bed
bed: "resources/paneldesign/S3287512_Covered-mod.bed"
bed_w_chr: "resources/paneldesign/S3287512_Covered.bed"

# path/to/mappability file
mappability: "resources/mappability/access-5k-mappable.hg19.bed"


### variance calling parameters: bcf tools

# bcftools call:
# caller: valid options include -c/--consensus-caller or -m/--multiallelic-caller
caller: "-m"
# other options e.g. "--ploidy 1 --prior 0.001"
caller_options: "--ploidy 1 --prior 0.001"

# bcftools mpileup:
# e.g. "--max-depth 100 --min-BQ 15"
mpileup_options: "--max-depth 100 --min-BQ 15"


